apiVersion: v1
kind: Service
metadata:
  name: openmrs-service
  labels:
    name: openmrs
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 8080
  selector:
    run: db1
