apiVersion: v1
kind: Pod
metadata:
  labels:
    run: db
  name: mariadb
spec:
  containers:
  - image: l00171152/wordpress:v1
    #  - image: l00171152/wordpress_db:latest
    name: db
    ports:
      - containerPort: 3306
    envFrom:
      - secretRef:
          name: please
