apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mongodb
  name: mongodb
spec:
  containers:
  - image: mongodb
    name: mongodb
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
